[{ "name": "Ultra", "russName": "Ультра", "logo": "http://web.meridianvk.com/img/radio/ultra2.png", "url": "http://94.25.53.133:80/ultra-192", "tags": "stream.php" },
{ "name": "Maximum", "russName": "Максимум", "logo": "http://web.meridianvk.com/img/radio/max.png", "url": "http://radio.north.kz:8000/rmaximum", "tags": "streamMax.php", hide_desktop: "1" },
{ "name": "Rock FM Ru", "russName": "Рок ФМ", "logo": "http://web.meridianvk.com/img/radio/rock.jpg", "url": "http://94.25.53.133/rock-192", "tags": "streamRockru.php" },
{ "name": "Nashe", "russName": "Наше", "logo": "http://web.meridianvk.com/img/radio/nashe.jpg", "url": "http://94.25.53.133/nashe-192", "tags": "streamNashe.php" },
{ "name": "RocketRadio", "russName": "Рокет", "logo": "http://web.meridianvk.com/img/radio/rocketRadio2.png", "url": "http://air.rocketradio.ru/256", "tags": "streamRocketRadio.php" },
{ "name": "42fm", "russName": "42fm", "logo": "http://web.meridianvk.com/img/radio/42.png", "url": "http://listen.42fm.ru:8000/stealkill", "tags": "tags42.php" },
{ "name": "Hitroe", "russName": "ХИТрое", "logo": "http://web.meridianvk.com/img/radio/hitr2.png", "url": "http://www.hitroe.com:8000/stream", "tags": "tagsHitroe.php" },
{ "name": "Grind.FM", "russName": "Grind.FM", "logo": "http://web.meridianvk.com/img/radio/grind.png", "url": "http://radio.goha.ru:8000/grind.fm", "tags": "grind.php" },
{ "name": "Radio Metal", "russName": "Radio Metal", "logo": "http://web.meridianvk.com/img/radio/metal.jpg", "url": 'http://alterhost.net:8000/radio-metal', "tags": 'metal.php' },
{ "name": "Rock.FM", "russName": "Rock.FM", "logo": "http://web.meridianvk.com/img/radio/rock2.png", "url": "http://216.235.94.10/play?s=wwwrockfm&d=LIVE365&r=0&membername=&session=wwwrockfm:0&AuthType=NORMAL&app_id=live365%3AWidget365&SaneID=89.218.116.130-1316542056143401&rnd=0.13509975979104638&tag=live365&caller=live365%3AWidget365&token=fa4005e3c52b134416c33a26be2b5bc8-1920290080101251", "tags": "streamRock.php" },
{ "name": "RelaxFM", "russName": "Релакс Фм", "logo": "http://web.meridianvk.com/img/radio/relax.png", "url": "http://live26.kiwi.kz:8000/relaxfm?type=.flv", "tags": "streamRelax.php" },
{ "name": "Europa plus", "russName": "Европа+", "logo": "http://web.meridianvk.com/img/radio/europa.png", "url": "http://webcast.emg.fm:55655/europaplus128.mp3", "tags": "streamEuropa.php", hide_desktop: "1" },
{ "name": "Sound Of Love", "russName": "Sound Of Love", "logo": "http://web.meridianvk.com/img/radio/slove.jpg", "url": "http://my.stepservice.ru:10149/love", "tags": "slove.php" },
{ "name": "Monte Carlo", "russName": "Монте Карло", "logo": "http://web.meridianvk.com/img/radio/monte.png", "url": "http://fm.kiwi.kz/montecarlospb", "tags": "streamMonte.php" },
{ "name": "Love Radio", "russName": "Love Radio", "logo": "http://web.meridianvk.com/img/radio/love.png", "url": "http://fm.kiwi.kz/loveradiokz", "tags": "streamLove.php" },
{ "name": "NRG Rock", "russName": "NRG Rock", "logo": "http://web.meridianvk.com/img/radio/energy.png", "url": "http://radio.mv.ru:8080/101.ru_NRJ_Rock", "tags": "streamEnergy.php" },
{ "name": "Mega Radio", "russName": "Мега", "logo": "http://web.meridianvk.com/img/radio/mega.png", "url": "http://radio.mv.ru:8080/MegaRadio", "tags": "streamMega.php" },
{ "name": "Radio Record", "russName": "Рекорд", "logo": "http://web.meridianvk.com/img/radio/record.png", "url": "http://online.radiorecord.ru:8101/rr_128?type=.mp3", "tags": "streamRecord.php" },
{ "name": "Alternative HD", "russName": "Alternative HD", "logo": "http://web.meridianvk.com/img/radio/alter.jpg", "url": "http://184.105.145.85:8000/;stream.nsv ", "tags": "streamAlter.php" },
{ "name": "Pianorama", "russName": "Pianorama (без тэгов)", "logo": "http://web.meridianvk.com/img/radio/pianorama.png", "url": "http://188.127.226.185/;stream.nsv", "tags": "" },

{ "name": "Radio ROKS", "russName": "ROKS(ua)", "logo": "http://web.meridianvk.com/img/radio/roksua.jpg", "url": 'http://online-radioroks.tavrmedia.ua/RadioROKS_256', "tags": 'roksua.php' },
{ "name": "Trancemission", "russName": "Trancemission", "logo": "http://web.meridianvk.com/img/radio/rectm.png", "url": 'http://online.radiorecord.ru:8102/tm_128?type=.mp3', "tags": 'record/streamtm.php' },
{ "name": "Pirate Station", "russName": "Pirate Station", "logo": "http://web.meridianvk.com/img/radio/recps.png", "url": 'http://online.radiorecord.ru:8102/ps_128?type=.mp3', "tags": 'record/streampt.php' },
{ "name": "Vip Mix", "russName": "Vip Mix", "logo": "http://web.meridianvk.com/img/radio/recvip.png", "url": 'http://online.radiorecord.ru:8102/vip_128?type=.mp3', "tags": 'record/streamvip.php' },
{ "name": "Teodor Hardstyle", "russName": "Teodor Hardstyle", "logo": "http://web.meridianvk.com/img/radio/recteo.png", "url": 'http://online.radiorecord.ru:8102/teo_128?type=.mp3', "tags": 'record/streamteo.php' },
{ "name": "Dancecore", "russName": "Dancecore", "logo": "http://web.meridianvk.com/img/radio/recdc.png", "url": 'http://online.radiorecord.ru:8102/dc_128?type=.mp3', "tags": 'record/streamdc.php' },
{ "name": "Breaks", "russName": "Breaks", "logo": "http://web.meridianvk.com/img/radio/recbrks.png", "url": 'http://online.radiorecord.ru:8102/brks_128?type=.mp3', "tags": 'record/streambrks.php' },
{ "name": "Chill-Out", "russName": "Chill-Out", "logo": "http://web.meridianvk.com/img/radio/recchil.png", "url": 'http://online.radiorecord.ru:8102/chil_128?type=.mp3', "tags": 'record/streamchil.php' },
{ "name": "Dubstep", "russName": "Dubstep", "logo": "http://web.meridianvk.com/img/radio/recdub.png", "url": 'http://online.radiorecord.ru:8102/dub_128?type=.mp3', "tags": 'record/streamdub.php' },

{ "name": "Es Radio", "russName": "Es Radio", "logo": "http://web.meridianvk.com/img/radio/esradio.jpg", "url": "http://188.134.24.54:8123/live", "tags": "esradio.php" },
{ "name": "KissFM", "russName": "KissFM", "logo": "http://web.meridianvk.com/img/radio/kissfm.jpg", "url": "http://stream.kissfm.ua:8000/kiss", "tags": "kissfm.php" },
{ "name": "djFM", "russName": "djFM", "logo": "http://web.meridianvk.com/img/radio/djfm.jpg", "url": "http://media.brg.ua:8010/;stream.nsv", "tags": "djfm.php" },
{ "name": "Alternative Rock", "russName": "Alternative Rock", "logo": "http://web.meridianvk.com/img/radio/skyfm.png", "url": "http://u16.sky.fm:80/sky_altrock", "tags": "/sky.fm/altRock.php" },
{ "name": "Christian Pop", "russName": "Christian Pop", "logo": "http://web.meridianvk.com/img/radio/skyfm.png", "url": "http://u16.sky.fm:80/sky_christian", "tags": "/sky.fm/christian.php" },
{ "name": "Classical Piano", "russName": "Classical Piano", "logo": "http://web.meridianvk.com/img/radio/skyfm.png", "url": "http://u16.sky.fm:80/sky_classicalpianotrios", "tags": "/sky.fm/classicalpianotrios.php" },
{ "name": "Hip Hop Rap", "russName": "Hip Hop Rap", "logo": "http://web.meridianvk.com/img/radio/skyfm.png", "url": "http://u16.sky.fm:80/sky_classicrap", "tags": "/sky.fm/classicrap.php" },
{ "name": "Classic Rock 70-80", "russName": "Classic Rock 70-80", "logo": "http://web.meridianvk.com/img/radio/skyfm.png", "url": "http://u16.sky.fm:80/sky_classicrock", "tags": "/sky.fm/classicrock.php" },
{ "name": "Electronic Chillout", "russName": "Electronic Chillout", "logo": "http://web.meridianvk.com/img/radio/skyfm.png", "url": "http://u16.sky.fm:80/sky_dreamscapes", "tags": "/sky.fm/dreamscapes.php" },
{ "name": "Flamenco Guitar", "russName": "Flamenco Guitar", "logo": "http://web.meridianvk.com/img/radio/skyfm.png", "url": "http://u16.sky.fm:80/sky_guitar", "tags": "/sky.fm/guitar.php" },
{ "name": "Indie Rock", "russName": "Indie Rock", "logo": "http://web.meridianvk.com/img/radio/skyfm.png", "url": "http://u16.sky.fm:80/sky_indierock", "tags": "/sky.fm/indierock.php" },
{ "name": "Japan Pop", "russName": "Japan Pop", "logo": "http://web.meridianvk.com/img/radio/skyfm.png", "url": "http://u16.sky.fm:80/sky_jpop", "tags": "/sky.fm/jpop.php" },
{ "name": "Love Romantic", "russName": "Love Romantic", "logo": "http://web.meridianvk.com/img/radio/skyfm.png", "url": "http://u16.sky.fm:80/sky_lovemusic", "tags": "/sky.fm/lovemusic.php" },
{ "name": "New Age Nature", "russName": "New Age Nature", "logo": "http://web.meridianvk.com/img/radio/skyfm.png", "url": "http://u16.sky.fm:80/sky_nature", "tags": "/sky.fm/nature.php" },
{ "name": "Pop Punk", "russName": "Pop Punk", "logo": "http://web.meridianvk.com/img/radio/skyfm.png", "url": "http://u16.sky.fm:80/sky_poppunk", "tags": "/sky.fm/poppunk.php" },
{ "name": "Solo Piano", "russName": "Solo Piano", "logo": "http://web.meridianvk.com/img/radio/skyfm.png", "url": "http://u16.sky.fm:80/sky_solopiano", "tags": "/sky.fm/solopiano.php" },
{ "name": "Soundtracks", "russName": "Soundtracks", "logo": "http://web.meridianvk.com/img/radio/skyfm.png", "url": "http://u16.sky.fm:80/sky_soundtracks", "tags": "/sky.fm/soundtracks.php" },
{ "name": "Bebop", "russName": "Bebop", "logo": "http://web.meridianvk.com/img/radio/skyfm.png", "url": "http://u16.sky.fm:80/sky_bebop", "tags": "/sky.fm/bepop.php" }]