var Echonest = {};
Echonest.genres = [{ "name": "8-bit","title":"8 бит" },
{ "name": "acoustic", "title": "Акустика" },
{ "name": "adult contemporary", "title": "Для 20-45 летних" },
{ "name": "alternative", "title": "Альтернатива" },
{ "name": "ambient", "title": "Эмбиент" },
{ "name": "americana", "title": "Американа" },
{ "name": "avant-garde", "title": "Авангард" },
{ "name": "ballad", "title": "Баллады" },
{ "name": "big band", "title": "Джаз оркестр" },
{ "name": "black metal", "title": "Блэк металл" },
{ "name": "bluegrass", "title": "Народная американская" },
{ "name": "blues", "title": "Блюз" },
{ "name": "bossa nova", "title": "Босса-нова" },
{ "name": "celtic", "title": "Кельтская" },
{ "name": "chanson", "title": "Шансон" },
{ "name": "christian", "title": "Христианская" },
{ "name": "classic rock", "title": "Классический рок" },
{ "name": "classical", "title": "Классическая" },
{ "name": "club", "title": "Клубная" },
{ "name": "comedy", "title": "Комедийная" },
{ "name": "country", "title": "Кантри" },
{ "name": "dance", "title": "Танцевальная" },
{ "name": "dark wave", "title": "Дарк Вэйв" },
{ "name": "death metal", "title": "Дэт метал" },
{ "name": "disco", "title": "Диско" },
{ "name": "drum and bass", "title": "Драм энд Басс" },
{ "name": "dub", "title": "Даб" },
{ "name": "electronic", "title": "Электроник" },
{ "name": "electronica", "title": "Электроника" },
{ "name": "electropop", "title": "Электро поп" },
{ "name": "emo", "title": "Эмо" },
{ "name": "experimental", "title": "Экспериментальная" },
{ "name": "female volcalists", "title": "Женский вокал" },
{ "name": "folk", "title": "Фолк" },
{ "name": "funk", "title": "Фанк" },
{ "name": "fusion", "title": "Фьюжн" },
{ "name": "glitch", "title": "Глитч" },
{ "name": "gothic", "title": "Готик" },
{ "name": "grunge", "title": "Гранж" },
{ "name": "guitar virtuoso", "title": "Гитарные виртуозы" },
{ "name": "gypsy", "title": "Джипси" },
{ "name": "hardcore", "title": "Хардкор" },
{ "name": "heavy metal", "title": "Хэви металл" },
{ "name": "hip hop", "title": "Хип - хоп" },
{ "name": "house", "title": "Хаус" },
{ "name": "indie", "title": "Инди" },
{ "name": "industrial", "title": "Индастриэл" },
{ "name": "instrumental", "title": "Инструментал" },
{ "name": "j-pop", "title": "Джей поп" },
{ "name": "j-rock", "title": "Джей рок" },
{ "name": "jazz", "title": "Джаз" },
{ "name": "kpop", "title": "Кей поп" },
{ "name": "latin", "title": "Латинская" },
{ "name": "lo-fi", "title": "Лоу фай" },
{ "name": "lounge", "title": "Лаундж" },
{ "name": "male vocalist", "title": "Мужской вокал" },
{ "name": "mediaeval", "title": "Средневековая" },
{ "name": "metal", "title": "Металл" },
{ "name": "new wave", "title": "Нью вэйв" },
{ "name": "noise", "title": "Нойз" },
{ "name": "old school", "title": "Олд скулл" },
{ "name": "opera", "title": "Опера" },
{ "name": "pop", "title": "Поп" },
{ "name": "psychedelic", "title": "Психоделика" },
{ "name": "punk", "title": "Панк" },
{ "name": "r&amp;b", "title": "Р&Б" },
{ "name": "rap", "title": "Рэп" },
{ "name": "reggae", "title": "Рэгги" },
{ "name": "rock", "title": "Рок" },
{ "name": "romantic", "title": "Романтическая" },
{ "name": "ska", "title": "Ска" },
{ "name": "soul", "title": "Соул" },
{ "name": "soundtrack", "title": "Саундтреки" },
{ "name": "style", "title": "Стильная" },
{ "name": "surf music", "title": "Сёрф рок" },
{ "name": "swing", "title": "Свинг" },
{ "name": "symphonic", "title": "Симфоническая" },
{ "name": "tango", "title": "Танго" },
{ "name": "techno", "title": "Техно" },
{ "name": "trance", "title": "Транс" },
{ "name": "trip hop", "title": "Трип хоп" }];


Echonest.moods = [{ "name": "aggressive", "title": "Агрессивное" },
{ "name": "ambient", "title": "Воздушное" },
{ "name": "angry", "title": "Злое" },
{ "name": "angst-ridden", "title": "Боязливое" },
{ "name": "bouncy", "title": "Резкое" },
{ "name": "calming", "title": "Спокойное" },
{ "name": "carefree", "title": "Беззаботное" },
{ "name": "cheerful", "title": "Веселое" },
{ "name": "cold", "title": "Холодное" },
{ "name": "complex", "title": "Смешанное" },
{ "name": "cool", "title": "Крутое" },
{ "name": "dark", "title": "Темное" },
{ "name": "disturbing", "title": "Тревожное" },
{ "name": "dramatic", "title": "Драматичное" },
{ "name": "dreamy", "title": "Мечтательное" },
{ "name": "eerie", "title": "Жуткое" },
{ "name": "elegant", "title": "Элегантное" },
{ "name": "energetic", "title": "Заряженное" },
{ "name": "enthusiastic", "title": "Энтузиазм" },
{ "name": "epic", "title": "Эпическое" },
{ "name": "fun", "title": "Развлекательное" },
{ "name": "funky", "title": "Довольное" },
{ "name": "futuristic", "title": "Футуристическое" },
{ "name": "gentle", "title": "Нежное" },
{ "name": "gleeful", "title": "Радостное" },
{ "name": "gloomy", "title": "Глумливое" },
{ "name": "happy", "title": "Счастливое" },
{ "name": "harsh", "title": "Суровое" },
{ "name": "haunting", "title": "Навязчивое" },
{ "name": "humorous", "title": "Юморное" },
{ "name": "hypnotic", "title": "Гипнотическое" },
{ "name": "intimate", "title": "Интимное" },
{ "name": "light", "title": "Светлое" },
{ "name": "lively", "title": "Живое" },
{ "name": "manic", "title": "Маниакальное" },
{ "name": "meditation", "title": "Медитативное" },
{ "name": "melancholia", "title": "Меланхолическое" },
{ "name": "mystical", "title": "Мистическое" },
{ "name": "ominous", "title": "Зловещее" },
{ "name": "party music", "title": "Клубное" },
{ "name": "passionate", "title": "Страстное" },
{ "name": "pastoral", "title": "Пасторальное" },
{ "name": "peaceful", "title": "Мирное" },
{ "name": "playful", "title": "Игривое" },
{ "name": "poignant", "title": "Острое" },
{ "name": "quiet", "title": "Тихое" },
{ "name": "rebellious", "title": "Мятежное" },
{ "name": "relax", "title": "Релаксирующее" },
{ "name": "romantic", "title": "Романтическое" },
{ "name": "rowdy", "title": "Криминальное" },
{ "name": "sad", "title": "Печальное" },
{ "name": "sentimental", "title": "Сентиментальное" },
{ "name": "sexy", "title": "Сексуальное" },
{ "name": "smooth", "title": "Ровное" },
{ "name": "sophisticated", "title": "Сложное" },
{ "name": "spacey", "title": "Космическое" },
{ "name": "spiritual", "title": "Спиритическое" },
{ "name": "strange", "title": "Странное" },
{ "name": "sweet", "title": "Сладкое" },
{ "name": "warm", "title": "Жаркое" },
{ "name": "whimsical", "title": "Причудливое" }]